### PR TITLE
Fixes snapping

### LINKED ISSUE #35: Snap to top of balls
Currently you can only snap to the bottom or sides of a ball.

### PR DESCRIPTION
**Pull request by iiKoe**
- Adds snapping to the roof
- Adds snapping to the top of balls

Fixes #35 and #26

### CODE REVIEW

File: core/src/com/group66/game/cannon/BallManager.java [hunk 1]
```diff
@@ -54,6 +54,9 @@
 	
 	/** The balls the canon will shoot. */
 	private ArrayList<Ball> cannonBallList = new ArrayList<Ball>();
+	
+	/** The roof hitbox offset. */
+	private float ROOF_OFFSET = 10;
```
Comment (11maxed11) [inline core/src/com/group66/game/cannon/BallManager.java]: Move to config maybe?

Comment (iiKoe) [inline core/src/com/group66/game/cannon/BallManager.java]: This is only useful for the roof hitbox, it wont be used anywhere else. So best to keep it here.
