### PR TITLE
Bug fix canon location

### LINKED ISSUE #27: Fix cannon center point
The cannon gets misaligned when rotating

### PR DESCRIPTION
**Pull request by 11maxed11**
Very simple merge.
Fixed #27

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -68,3 +68,4 @@ build/
 ## OS Specific
 .DS_Store
 Thumbs.db
+core/src/com/group66/game/cannon/Cannon.java
```
Comment (iiKoe) [inline .gitignore]: ???? We ignore the Cannon.java file

Comment (11maxed11) [inline .gitignore]: No we don't
This is was done by mistake when solving a previous conflict error
Fixed now

File: core/src/com/group66/game/cannon/Cannon.java [hunk 2]
```diff
@@ -137,14 +137,8 @@ public void update(float delta) {
...
     public void draw(SpriteBatch batch) {
-        //batch.draw(cannon_texture, hitbox.x, hitbox.y, BALL_RAD, BALL_RAD);
-
-        batch.draw(cannonTextureRegion, xpos - width / 2f - 3, ypos - height / 2f + 23, 
-                width / 2f, height / 2f, width, height, 5 / 2, 1, angle, true);
-
-        //batch.draw(cannon_texture_region, x - width / 2f, y - height / 2f,    
-        //width / 2f, height / 2f, width, height, 1, 1, angle, true);
-
+        batch.draw(cannonTextureRegion, xpos - width / 2f + 11, ypos - height / 2f + 7,
```
Comment (iiKoe) [inline core/src/com/group66/game/cannon/Cannon.java]: What are those magic numbers? Can they be eliminated by using height and width? (The whole idea is that another texture would not require a change of code here, only a change of cannonTextureRegion)

Comment (11maxed11) [inline core/src/com/group66/game/cannon/Cannon.java]: They are just some small and different offsets to put the cannon in a good location and re-locate the rotation point to a place different than the cannon center (since it should rotate around a specific rotation point that's not exactly the center at height/2)
And nop they can't be eliminated by using height and width

Comment (iiKoe) [inline core/src/com/group66/game/cannon/Cannon.java]: I guess the best option then is to change the texture sprite so the rotational center is in the center, this makes it so we can just use another cannon sprite without changing the code. (We could just add transparent pixels at the bottom or top wherever needed in the image to make it centered)

Comment (11maxed11) [inline core/src/com/group66/game/cannon/Cannon.java]: Agree. I tried changing the sprite shape to another shape (that's why this part took some extra time with me) but couldn't get a design that's centered. Might follow the transparent pixels idea of yours.
Will check and get back with a commit later.

Comment (11maxed11) [inline core/src/com/group66/game/cannon/Cannon.java]: Fixed. Please approve.
