### PR TITLE
Bug/infinite loop when game ends

### LINKED ISSUE #113: Mute doesn't work on the very first screen in the game (the newly introduced one)
And the music is too annoying to ignore this issue

### PR DESCRIPTION
**Pull request by jeroenoverman**
- changed when the next ball of the canon is draw. Now after the grid is updated from last ball shot.
- fixed the infinte loop when only bombballs were left in the grid.
- fixed the mute button in the start screen.
- fixed loading user profile.
- DynamicSettings is now an object of the game instance. can be retrieved by a getter method
- ProfileManager is now an object of the game instance. can be retrieved by a getter method.
- fixed that the ball is shot automatically 10 seconds after the ball attached to the grid.

closes #113 #89 #116

### CODE REVIEW

File: core/src/com/group66/game/screens/StartScreen.java [hunk 1]
```diff
@@ -109,19 +109,39 @@ public void setupButtons() {
...
-                NameInputListener listener = new NameInputListener(dynamicSettings);
+                NameInputListener listener = new NameInputListener(BustaMove.getGameInstance().getDynamicSettings());
                 Gdx.input.getTextInput(listener, "Enter your name", "", "");
             }
         });
         startButton.addListener(new ChangeListener() {
             public void changed(ChangeEvent event, Actor actor) {
-                if (!dynamicSettings.getName().equals("")) {
-                    BallAnimationLoader.profileManager.readData(dynamicSettings.getName(), dynamicSettings);
+                if (!BustaMove.getGameInstance().getDynamicSettings().getName().equals("")) {
```
Comment (ALobker) [inline core/src/com/group66/game/screens/StartScreen.java]: Correct way should be: !"".equals(BustaMove.getGameInstance().getDynamicSettings().getName())
Because getName could be null, causing a null pointer exception. It feels weird, but it is safer.

File: core/src/com/group66/game/screens/ThreePlayerGameScreen.java [hunk 2]
```diff
@@ -23,25 +23,19 @@
...
      */
-    public ThreePlayerGameScreen(Boolean randomLevel, DynamicSettings dynamicSettings) {
+    public ThreePlayerGameScreen(Boolean randomLevel) {
         gameState = GameState.RUNNING;
         inputHandler = new InputHandler();
-        this.dynamicSettings = dynamicSettings;
-        ballManager1 = new BallManager(0, dynamicSettings);
-        ballManager2 = new BallManager(2, dynamicSettings);
-        ballManager3 = new BallManager(1, dynamicSettings);
+        ballManager1 = new BallManager(0, BustaMove.getGameInstance().getDynamicSettings());
```
Comment (ALobker) [inline core/src/com/group66/game/screens/ThreePlayerGameScreen.java]: No need to pass the second parameter

File: core/src/com/group66/game/screens/ThreePlayerGameScreen.java [hunk 3]
```diff
@@ -58,13 +52,16 @@ public ThreePlayerGameScreen(Boolean randomLevel, DynamicSettings dynamicSetting
...
         }
+        ballManager1.addRandomBallToCanon();
+        ballManager2.addRandomBallToCanon();
+        ballManager3.addRandomBallToCanon();
     }
     
     /**
      * Instantiates the game screen.
      */
     public ThreePlayerGameScreen(DynamicSettings dynamicSettings) {
```
Comment (ALobker) [inline core/src/com/group66/game/screens/ThreePlayerGameScreen.java]: Remove

File: core/src/com/group66/game/screens/TwoPlayerGameScreen.java [hunk 4]
```diff
@@ -54,13 +48,15 @@ public TwoPlayerGameScreen(Boolean randomLevel, DynamicSettings dynamicSettings)
...
             BustaMove.getGameInstance().log(MessageType.Info, "Loaded a random level");
         }
+        ballManager1.addRandomBallToCanon();
+        ballManager2.addRandomBallToCanon();
     }
     
     /**
      * Instantiates the game screen.
      */
     public TwoPlayerGameScreen(DynamicSettings dynamicSettings) {
```
Comment (ALobker) [inline core/src/com/group66/game/screens/TwoPlayerGameScreen.java]: Remove

File: core/src/com/group66/game/shop/BuyScoreMultiplier.java [hunk 5]
```diff
@@ -26,8 +26,8 @@ public BuyScoreMultiplier() {
          */
         public void buy(BuyStateInstance instance, DynamicSettings dynamicSettings) {
```
Comment (ALobker) [inline core/src/com/group66/game/shop/BuyScoreMultiplier.java]: No need to pass dynamicSettings as parameter

File: core/src/com/group66/game/screens/ThreePlayerGameScreen.java (hunk 2 above)
Comment (jeroenoverman) [inline core/src/com/group66/game/screens/ThreePlayerGameScreen.java]: I left this, so we could make different dynamicSettings for each split player.

File: core/src/com/group66/game/screens/StartScreen.java (hunk 1 above)
Comment (jeroenoverman) [inline core/src/com/group66/game/screens/StartScreen.java]: agree. fixed

File: core/src/com/group66/game/screens/OnePlayerGameScreen.java [hunk 6]
```diff
@@ -22,42 +22,39 @@
...
             LevelLoader.generateLevel(ballManager, false);
             BustaMove.getGameInstance().log(MessageType.Info, "Loaded a random level");
         }
+        ballManager.addRandomBallToCanon();
     }
 
     /**
      * Instantiates the game screen.
      */
     public OnePlayerGameScreen(DynamicSettings dynamicSettings) {
```
Comment (jeroenoverman) [inline core/src/com/group66/game/screens/OnePlayerGameScreen.java]: removed the argument.

File: core/src/com/group66/game/screens/ThreePlayerGameScreen.java (hunk 3 above)
Comment (jeroenoverman) [inline core/src/com/group66/game/screens/ThreePlayerGameScreen.java]: why?

File: core/src/com/group66/game/shop/BuyScoreMultiplier.java (hunk 5 above)
Comment (jeroenoverman) [inline core/src/com/group66/game/shop/BuyScoreMultiplier.java]: Yes we need to. Because there could be multiple instances of dynamicSettings. Its not a singleton.

**Comment by ALobker** [comment]
I thought dynamicsettings were for all players, but for each player separately makes sense.

File: core/src/com/group66/game/screens/ThreePlayerGameScreen.java (hunk 3 above)
Comment (ALobker) [inline core/src/com/group66/game/screens/ThreePlayerGameScreen.java]: This referred only to the last line, not sure why the whole block was selected

**Comment by 11maxed11** [comment]
Tested, works well.
